FROM res-drl-hpc-docker-local.artifactory.swg-devops.com/spark:v3.0.0 AS build

USER root

ENV TPCDS_HOME=/opt/spark-tpc-ds-performance-test

RUN apt-get update && \
    apt-get -y install gcc make flex bison byacc git curl gnupg && \
    echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add && \
    apt-get update && \
    apt-get install sbt && \
    mkdir -p ${TPCDS_HOME} 

COPY . ${TPCDS_HOME}

RUN cd ${TPCDS_HOME} && \ 
    sbt package 

#Compile the TPC DS tools
RUN cd ${TPCDS_HOME}/src/toolkit/tools && \
    make clean && \
    make OS=LINUX

FROM res-drl-hpc-docker-local.artifactory.swg-devops.com/spark:v3.0.0

ENV SPARK_HOME=/opt/spark
ENV TPCDS_HOME=/opt/spark/tpc-ds-performance-test
ENV PATH=${SPARK_HOME}/bin:${PATH}

USER root
RUN apt-get update && apt-get install -y procps

COPY . ${TPCDS_HOME}
WORKDIR ${TPCDS_HOME}

COPY --from=build /opt/spark-tpc-ds-performance-test/src/toolkit/tools ${TPCDS_HOME}/src/toolkit/tools/
COPY --from=build /opt/spark-tpc-ds-performance-test/target/scala-2.12/tpc-ds-benchmark-perf_2.12-0.1.jar ${TPCDS_HOME}
COPY --from=build /opt/spark-tpc-ds-performance-test/src/ddl ${TPCDS_HOME}/ddl

RUN groupadd -r tpcds --gid=185 && \
    mkdir -p ${TPCDS_HOME}/work && \
    useradd -r -g tpcds --uid=185 -d ${SPARK_HOME} tpcds && \
    chown tpcds:tpcds -R ${TPCDS_HOME} && \
    chown tpcds:tpcds -R ${SPARK_HOME}
USER tpcds

#Configure tpcdsenv.sh
#We will statically define tpcdsenv.sh
ENTRYPOINT [ "/opt/spark-tpc-ds-performance-test/bin/tpcdsspark.sh" ]
CMD ["3"]
