---
apiVersion: v1
kind: Service
metadata:
  name: spark-dlf-svc
spec:
  type: "ClusterIP"
  clusterIP: "None"
  selector:
    app: spark-dlf-driver
  ports:
    - port: 20020
      targetPort: 20020
      name: spark-driver
---
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-ui
spec:
  type: "NodePort"
  selector:
    app: spark-dlf-driver
  ports:
    - port: 8966
      targetPort: 4040
      name: spark-ui
---
apiVersion: v1
kind: Pod
metadata:
  name: spark-dlf-runner
  labels:
    app: spark-dlf-v-runner
spec:
  serviceAccountName: spark-dlf
  imagePullSecrets:
    - name: evolve-reg
  containers:
    - name: spark-tpcds1g
      image: 172.9.0.240:5000/dlf/tpcds-perf-test:latest 
      imagePullPolicy: Always
      args:
        - /opt/spark/bin/spark-submit
        - --master
        - k8s://https://$(KUBERNETES_PORT_443_TCP_ADDR):$(KUBERNETES_PORT_443_TCP_PORT)
        - --deploy-mode
        - cluster
        - --conf
        - spark.kubernetes.container.image=172.9.0.240:5000/dlf/tpcds-perf-test:latest
        - --conf
        - spark.kubernetes.container.image.pullPolicy=Always
        - --conf
        - spark.kubernetes.container.image.pullSecrets=evolve-reg
        - --conf
        - spark.kubernetes.namespace=dlf
        - --conf
        - spark.kubernetes.authenticate.driver.serviceAccountName=spark-dlf
        - --conf
        - spark.kubernetes.driver.pod.name=spark-dlf-driver
        - --conf
        - spark.driver.host=spark-dlf-svc.default.svc.cluster.local
        - --conf
        - spark.driver.port=20020
        - --conf
        - spark.driver.cores=4 
        - --conf 
        - spark.driver.memory=16g
        - --conf
        - spark.jars.ivy=/tmp/.ivy
        - --conf
        - spark.kubernetes.driver.podTemplateFile=/opt/spark/tpc-ds-performance-test/podtemplate-volcano.yaml
        - --conf
        - spark.kubernetes.driver.label.dataset.0.id=dfc77721
        - --conf
        - spark.kubernetes.driver.label.dataset.0.useas=mount
        - --conf
        - spark.driver.maxResultSize=4g
        - --conf 
        - spark.executor.instances=8 
        - --conf
        - spark.executor.cores=4 
        - --conf 
        - spark.executor.memory=16g
        - --conf
        - spark.kubernetes.executor.podTemplateFile=/opt/spark/tpc-ds-performance-test/podtemplate-volcano.yaml
        - --conf
        - spark.kubernetes.executor.label.dataset.0.id=dfc77721
        - --conf
        - spark.kubernetes.executor.label.dataset.0.useas=mount
        - --class
        - SparkRunner
        - local:///opt/spark/tpc-ds-benchmark-perf_2.12-0.1.jar 
        - "/mnt/datasets/dfc77721" 
        - "dfc77721"
        - "/opt/spark/work"
        - "/opt/spark/warehouse"
        - "3"
